 apiVersion: extensions/v1beta1
 kind: Ingress
 metadata:
   name: my-ingres
 spec:
   tls:
   - hosts:
     - iks1.jp-tok.containers.appdomain.cloud
     secretName: iks1
   rules:
   - host: iks1.jp-tok.containers.appdomain.cloud
     http:
       paths:
       - path: /
         backend:
           serviceName: web-svc
           servicePort: 9080
